# Generated by Django 2.2 on 2020-07-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors_app', '0002_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='Not provided'),
        ),
    ]
